language: python
python:
- '3.4'
- 3.5-dev
script: python manage.py test
addons:
  postgresql: '9.4'
before_script:
- psql -c 'create database "test-database";' -U postgres
env: FLASK_CONFIG=testing
deploy:
  provider: heroku
  app: afternoon-gorge-4661
  api_key:
    secure: J+CyxqZ/Jo8BOvLDVAegdW5XT/ME9WUUfQB/fSKii9AJhcEppuZiPsULy0VCJ/E9zvvCZ5SrAvC8Md++V6+5FsAyKKONv+cVPBNQbAtbR61CftJHeIWmzDT20X93YUnI44OULh75KDJ5XPoRxEhq5jLgpAL/wCSMDGOqwHaq7RKWoepVyhsAGVLUMjNBrFlM/479OEp1NmPSNehWyY+JsHQM4IK/lrUpwwdKMVDmAJj2dvTCq2VVHvNCjuR6OFzTdqh75nhlST0b0GBZya4oG15EXTkCdU44aZIxphpLrMyueSs3M5rh62HsZF2L8x0an2SXdl7nO182nXvUoc+aDvw+Q3HxF82AjZaDSSDfgiE7VJ28vZ1ELsWh0jDXBQkMG+98w6QtiAGb4Xx1JnWgX5BXKVEikDuEImxOZqR60b9U2WYEZ8xdfA2ZypvjRE7YFkaMdHIOQOnBEVBFFF17JskM59THtrUOGyOq94h2FLEQMj+52le2FrG61bIYPwG2F6A2Isu8UdcNcRCWh7qqAVgHRN+3oiONYD118hfSn1MXL8a7D5hr7VeAGXviUuHnmjaIOwbco1SI6RW9ajymjm19z20N4og+yu2EQbFbg0AOD/q48DZ/H6T9bySYeSPvOWTckGMG3YCc0t66l9X2nCJ0xbf3n4EelM8SDh3R9LU=
cache: pip
