language: python
python:
- '3.5'
script: python manage.py test
addons:
  postgresql: '9.4'
before_script:
- psql -c 'create database "test-database";' -U postgres
env: FLASK_CONFIG=testing
cache: pip
