language: python
python:
  - '3.5'
install:
  - pip install -U pip
  - pip install -r requirements.txt
script: python manage.py test
addons:
  postgresql: '9.4'
before_script:
  - psql -c 'create database "test-database";' -U postgres
  - npm install -g bower
  - bower install
  - npm install
  - npm install -g gulp
  - gulp build
env: FLASK_CONFIG=testing
cache:
  directories:
    - $HOME/.cache/pip
    - node_modules
    - app/static/vendor
