language: python
python:
    - "2.7"
    - "3.4"
    - "3.5-dev"
    - "nightly"
script: python manage.py test
addons:
    postgresql: "9.4"
before_script:
    - psql -c 'create database "test-database";' -U postgres
