"""Add administration fee

Revision ID: 1690d6c632c
Revises: None
Create Date: 2015-08-24 12:56:31.733270

"""

# revision identifiers, used by Alembic.
revision = '1690d6c632c'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('admin_fee', sa.Float(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'admin_fee')
    ### end Alembic commands ###
