"""Add refrence numbers

Revision ID: 43f17068214
Revises: d5efe6ee70
Create Date: 2015-08-31 14:43:12.574896

"""

# revision identifiers, used by Alembic.
revision = '43f17068214'
down_revision = 'd5efe6ee70'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('reference_number', sa.String(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'reference_number')
    ### end Alembic commands ###
